AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TagName:
    Type: String
    Description: Provide a Tag name to identify the Infrastructure
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  ClusterName:
    Type: String
    Description: Name of ECS Cluster
  AsgDesiredCapacity:
    Type: Number
    Default: '2'
    Description: Number of instances to launch in your ECS cluster.
  AsgMaxSize:
    Type: Number
    Default: '3'
    Description: Maximum number of instances that can be launched in your ECS cluster.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large]
    ConstraintDescription: Please choose a valid instance type.
  PrivateSubnetAZ1:
    Description: Availability Zone ID private subnet 1.
    Type: String
  PrivateSubnetAZ2:
    Description: Availability Zone ID private subnet 2.
    Type: String
  PrivateSecurityGroupID:
    Description: Private Security Group ID for instances.
    Type: String
Mappings:
  AWSRegionToAMI:
    ap-northeast-1:
        AMIID: ami-30bdce57
    ap-southeast-1:
        AMIID: ami-9f75ddfc
    ap-southeast-2:
        AMIID: ami-cf393cac
    us-east-1:
        AMIID: ami-a58760b3
    us-east-2:
        AMIID: ami-a6e4bec3
    us-west-1:
        AMIID: ami-74cb9b14
    us-west-2:
        AMIID: ami-5b6dde3b
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
     ClusterName: !Ref 'ClusterName'
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnetAZ1
        - !Ref PrivateSubnetAZ2
      LaunchConfigurationName: !Ref 'ECSAutoscalingLC'
      MinSize: '1'
      MaxSize: !Ref 'AsgMaxSize'
      DesiredCapacity: !Ref 'AsgDesiredCapacity'
  ECSAutoscalingLC:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      ImageId: !FindInMap [AWSRegionToAMI, !Ref 'AWS::Region', AMIID]
      SecurityGroups:
        - !Ref PrivateSecurityGroupID
      InstanceType: !Ref 'InstanceType'
      IamInstanceProfile: !Ref 'EC2InstanceProfile'
      KeyName: !Ref 'KeyName'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
  ECSServicePolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: ['ecs:*', 'logs:*']
            Resource: '*'
      Roles: [!Ref 'EC2Role']
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref 'EC2Role']
  ECSScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: ECSAutoScalingGroup
      Cooldown: '300'
      ScalingAdjustment: '1'
  ECSCPUScaleUpAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '80'
      AlarmDescription: Alarm if ECS Cluster CPU reservation goes above 80
      Period: '300'
      AlarmActions: [!Ref 'ECSScaleUpPolicy']
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Ref: ECSCluster
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUReservation
  ECSMemoryScaleUpAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '80'
      AlarmDescription: Alarm if ECS Cluster Memory reservation goes above 80
      Period: '300'
      AlarmActions: [!Ref 'ECSScaleUpPolicy']
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value:
          Ref: ECSCluster
      ComparisonOperator: GreaterThanThreshold
      MetricName: MemoryReservation
Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref 'ClusterName' 
