  
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/S3_BUCKET_NAME/templates/ecs/ecs.yaml
      Parameters:
        TagName: !Ref 'TagName'
        PrivateSubnetAZ1: !GetAtt Infrastructure.Outputs.PrivateSubnetAZ1
        PrivateSubnetAZ2: !GetAtt Infrastructure.Outputs.PrivateSubnetAZ2
        PrivateSecurityGroupID: !GetAtt Infrastructure.Outputs.PublicSecurityGroup
        KeyName: !Ref 'KeyName'
        ClusterName: !Ref 'ClusterName'
        AsgDesiredCapacity: !Ref 'AsgDesiredCapacity'
        AsgMaxSize: !Ref 'AsgMaxSize'
        InstanceType: !Ref 'InstanceType'
