AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ECSCluster:
    Type: String
    Description: Name of an existing ECS Cluster.
  TaskDefinition:
    Type: String
    Description: Name of Task Definition
Resources:
  service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ECSCluster'
      DesiredCount: '1'
      TaskDefinition: !Ref 'TaskDefinition'
Outputs:
  ecsservice:
    Value: !Ref 'service'
