AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TagName:
    Type: String
    Description: Tag Name of your Infrastructure. 
  ECSCluster:
    Type: String
    Description: Name of an existing ECS Cluster.
Resources:
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [NginxLogGroup, !Ref 'AWS::StackName']]
      RetentionInDays: 14
  Nginxtaskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Nginx-ng
      ContainerDefinitions:
      - Name: nginx
        Cpu: '10'
        Essential: 'true'
        Image: nginx
        Memory: '128'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'CloudwatchLogsGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: nginx
        PortMappings:
        - ContainerPort: 80
          HostPort: 80
      Volumes:
      - Name: my-vol
  NginxService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ECSCluster'
      DesiredCount: '1'
      TaskDefinition: !Ref 'Nginxtaskdefinition'
Outputs:
  ecsservice:
    Value: !Ref 'NginxService'
