  
  Nginx:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/S3_BUCKET_NAME/templates/nginx/nginx.yaml
      Parameters:
        TagName: !Ref 'TagName'
        ECSClusterName: !GetAtt 'ECS.Outputs.ECSClusterName'
