AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TagName:
    Type: String
    Description: TagName of your Infrastructure.
  ECSCluster:
    Type: String
    Description: Name of an existing ECS Cluster.
Resources:
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [ECSLogGroup, !Ref 'AWS::StackName']]
      RetentionInDays: 14
  Tyktaskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Tyk
      ContainerDefinitions:
      - Name: tyk-hybrid
        Cpu: '1024'
        Essential: 'true'
        Image: tykio/tyk-hybrid-docker
        Memory: '512'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'CloudwatchLogsGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: tyk
        PortMappings:
        - ContainerPort: 8181
          HostPort: 8181
        - ContainerPort: 9090
          HostPort: 9090
        Environment:
        - Name: APIKEY
          Value: api_key
        - Name: BINDSLUG
          Value: 1
        - Name: DISABLENGINX
          Value: 1
        - Name: PORT
          Value: 8181
        - Name: REDISHOST
          Value: resdis_host_name
        - Name: RPORT
          Value: 6379
        - Name: SECRET
          Value: secret
      Volumes:
      - Name: my-vol
  Tykservice:
    Type: AWS::ECS::Service
    DependsOn: ALBListener
    Properties:
      Cluster: !Ref 'ECSCluster'
      DesiredCount: '1'
      LoadBalancers:
      - ContainerName: tyk-hybrid
        ContainerPort: '8181'
        TargetGroupArn: !Ref 'ECSTG'
      Role: !Ref 'ECSServiceRole'
      TaskDefinition: !Ref 'Tyktaskdefinition'
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
  ECSServicePolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "ecs-service"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: ['elasticloadbalancing:*', 'ec2:*']
            Resource: '*'
      Roles: [!Ref 'ECSServiceRole']
  TykALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: TykALB
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Subnets: 
        - Fn::ImportValue:
            Fn::Sub: "${TagName}-PublicSubnetAZ1ID"
        - Fn::ImportValue:
            Fn::Sub: "${TagName}-PublicSubnetAZ2ID"
      SecurityGroups:
        - Fn::ImportValue:
            Fn::Sub: "${TagName}-PublicSecurityGroupID"
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ECSServiceRole
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref 'ECSTG'
      LoadBalancerArn: !Ref 'TykALB'
      Port: '80'
      Protocol: HTTP
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ALBListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'ECSTG'
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref 'ALBListener'
      Priority: 1
  ECSTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: TykALB
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: ECSTG
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${TagName}-VpcId"
Outputs:
  ecsservice:
    Value: !Ref 'Tykservice'
